# Generated by Django 2.1.8 on 2019-05-22 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrap', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='scrap',
            old_name='body',
            new_name='description',
        ),
        migrations.AlterField(
            model_name='scrap',
            name='preview',
            field=models.ImageField(upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='scrap',
            name='title',
            field=models.CharField(max_length=250),
        ),
    ]
